markdown: kramdown

includes_dir: .

permalink: /blog/:month-:day-:year/:title/

# Main site navigation.
# Layouts and pages can include nav_items array referring to link IDs in frontmatter
nav:
  home:
    url: /
    title: Home
  about:
    url: /about
    title: About

# Footer navigation
footer_nav:
  - url: https://committee.iso.org/home/tc211
    title: ISO/TC 211

collections:
  pages:
    output: true
    permalink: /:path/

exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
