title: "An ISO TC 211 site"

email: open.source@ribose.com

description: >-
  Welcome to this ISO/TC 211 site.

# The protocol + domain name of the site
# url: "https://geolexica.com"

includes_dir: .

markdown: kramdown

permalink: /blog/:month-:day-:year/:title/

# Social profile navigation
# social:
#   links:
#     - url: https://twitter.com/…
#     - url: https://github.com/…
#     - url: https://www.facebook.com/groups/…
#     - url: https://www.linkedin.com/groups/…

# committee:
#   id: <number>
#   name: <full name>
#   home: <committee’s external home page URL>
#   links:
#     - url: /about
#       title: About
#     - url: /strategic-policy
#       title: Strategic Policy Statement
#     - url: /faq
#       title: FAQ

# Main site navigation.
# Layouts and pages can specify priority nav items
# using frontmatter key nav_items
# pointing to an array listing nav item IDs.
nav:
  items:
    - id: home
      url: /
      title: Home
      description: Standard&nbsp;resources &amp;&nbsp;latest&nbsp;news
    - id: about
      url: /about
      title: About

# Footer navigation
footer_nav:
  - url: https://committee.iso.org/home/tc211
    title: ISO/TC 211

collections:
  pages:
    output: true
    permalink: /:path/

exclude:
  - Gemfile
  - Gemfile.lock
  - .sass-cache/
