=== Changelog

== 0.4

Redesigned site header. Added header menu (triggered by hamburger icon)
with links for navigation across the site and ISO TC pages.

Added news (blog) index page.

Fixed some minor layout issues with the site.

== 0.3.1

Improved typography legibility & added more extensive support for AsciiDoc-generated blocks.

Corrected minor issues with newsroll carousel and awards banner.

== 0.3

Improved general site aesthetics, adding color accent and making whitespace
more consistent.

Supporting showing ISO TC award notice and newsroll entry timestamps.

== 0.2.4

Now showing news entry date on publication page.

Fixed an issue with newsroll layout on landing page with narrower viewports.

== 0.2.3

Support posts with illustrations.

== 0.2.2

Hide news block if site has no posts.

== 0.2.1

Small fix in which home template allows site index page to specify content
to go before the news section.

== 0.2

An update to overall layout that also fixes some issues on narrow screens.

== 0.1.4

Minor fixes including title bar phrasing and site branding typography.

== 0.1.3

Included Normalize.css to add cross-browser appearance consistency.

Cleaned up some of remaining Geolexica-specific style rules.

== 0.1.2

Removed a few leftovers inherited while theme was getting abstracted out of the Geolexica site.

== 0.1.1

First implementation.
