=== Changelog

== 0.5.3

Fixed an issue with Blueprint CSS, used for resource browser widget,
affecting the appearance of the rest of the page.

== 0.5.2

Fixed an issue where resource browser may not work due to a silly syntax error.

== 0.5.1

Added an include to make `<title>` meta tag easily overridable.

== 0.5.0

Resource navigator graduated to beta. Fixed compatibility issues with Firefox,
some appearance regressions, and increased robustness overall.

== 0.4.9

Implemented resource navigation UI for things like standards, schemas, ontologies
and so on.

- Resources are configured via site’s _config.yml.

- For each resource listing, root directory
  is specified, under which each direct subdirectory is treated as an individual resource,
  and anything nested under it is treated as resource contents and can be arbitrary.

- For each resource listing, under specified path, site provides a tree view of resource
  content structure, allowing to easily access any file.

- Resource pages pull BlueprintJS’s styling for the tree view widget.

== 0.4.8

Added a setting to specify Font Awesome kit URL,
according to their new distribution method.

== 0.4.7

Added styling for external links added by jekyll-external-links.

== 0.4.4/0.4.6

Added support for Google Analytics.

Improved layout compatibility with IE10+.

== 0.4.3

Added an option to configure Committee site link in main navigation.
The option, when switched to yes, will ensure committee site link
will always appear on landing, regardless of top expandable menu state.

== 0.4.1/0.4.2

Layout fixes related to Flexbox layout behavior in IE 11, 10 and 9.

== 0.4

Redesigned site header. Added header menu (triggered by hamburger icon)
with links for navigation across the site and ISO TC pages.

Added news (blog) index page.

Added base-page template with generalized page header markup,
and corresponding style rules.

Fixed some minor layout issues with the site.

== 0.3.1

Improved typography legibility & added more extensive support for AsciiDoc-generated blocks.

Corrected minor issues with newsroll carousel and awards banner.

== 0.3

Improved general site aesthetics, adding color accent and making whitespace
more consistent.

Supporting showing ISO TC award notice and newsroll entry timestamps.

== 0.2.4

Now showing news entry date on publication page.

Fixed an issue with newsroll layout on landing page with narrower viewports.

== 0.2.3

Support posts with illustrations.

== 0.2.2

Hide news block if site has no posts.

== 0.2.1

Small fix in which home template allows site index page to specify content
to go before the news section.

== 0.2

An update to overall layout that also fixes some issues on narrow screens.

== 0.1.4

Minor fixes including title bar phrasing and site branding typography.

== 0.1.3

Included Normalize.css to add cross-browser appearance consistency.

Cleaned up some of remaining Geolexica-specific style rules.

== 0.1.2

Removed a few leftovers inherited while theme was getting abstracted out of the Geolexica site.

== 0.1.1

First implementation.
